server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/outageDB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

incident:
  service:
    name: incident-management-service

jwt:
  secret: change-me-super-secret
